apiVersion: v1
kind: Service
metadata:
  name: dataloader-service-gpu
  labels:
    app: dataloader-service-gpu
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: dataloader-service-gpu
